HEADERS := ../hash/hash.h ../list/list.h ../huff_tree/huff_tree.h
SRC := ../hash/hash.c ../list/list.c ../huff_tree/huff_tree.c
MAIN := compressao.c

compile:
	gcc $(HEADERS) $(SRC) $(MAIN) -o a.out -lm -Wall