HEADERS := ../hash/hash.h ../list/list.h ../huff_tree/huff_tree.h ../files/files.h
SRC := ../hash/hash.c ../list/list.c ../huff_tree/huff_tree.c ../files/files.c
MAIN := descompressao.c

compile:
	gcc $(HEADERS) $(SRC) $(MAIN) -o a.out -lm